[project]
name = "variable-patchtst-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ethan Russell", email = "ecr84@cornell.edu" }
]
dependencies = [
    "kagglehub",
    "numpy",
    "pandas",
    "torch",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["variable_patchtst_project*"]